services:

  postgres:
    image: acaimari/sportsclub-postgres:latest
    # build: !reset []
    env_file:
      - .env.production
    environment: !reset []
    restart: always
    ports: !reset []
  app-blue:
    image: acaimari/sportsclub-app:latest
    build: !reset []
    env_file:
      - .env.production
    environment: !reset []
    restart: always
  app-green:
    image: acaimari/sportsclub-app:latest
    build: !reset []
    env_file:
      - .env.production
    environment: !reset []
    restart: always
  nginx:
    build: !reset []
    image: acaimari/sportsclub-nginx:latest
    ports: !override
      - "80:80"
    restart: always
